CREATE TABLE ORDERS(
ID NUMBER,
USER_ID NUMBER,
CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
ROOM_ID NUMBER,
CONSTRAINT ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
DATEFROM TIMESTAMP,
DATETO TIMESTAMP,
MONEYPAID NUMBER(5,2)
)