CREATE TABLE USERS(
ID NUMBER,
CONSTRAINT USER_ID PRIMARY KEY(ID),
USERNAME NVARCHAR2(50),
PASSWORD NVARCHAR2(50),
COUNTRY NVARCHAR2(20),
USERTYPE NUMBER DEFAULT 1,
CONSTRAINT USERTYPE_CHECK CHECK(USERTYPE=0 OR USERTYPE=1)

)